### ISSUE TITLE
v1.4.0 tag を push してほしいです。またリリース処理もお願いしたいです。

### ISSUE THREAD

**Issue by yabuki** [deton/eblook.vim#5]
たぶん、push し忘れだと思うのですが、

v1.4.0 が更新履歴に載っています。しかし、GitHub へ tagとしてpush されていません。
また、GitHubでのリリース処理も、よろしくお願いします。

`git push origin v1.4.0` または `git push origin --tags`

**Comment by deton** [comment]
対応しておきました。

**Comment by yabuki** [comment]
ありがとうございます！
